version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: num_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: num_db
      MYSQL_USER: num_user
      MYSQL_PASSWORD: num_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: num_backend
    restart: always
    environment:
      DB_HOST: db
      DB_USER: num_user
      DB_PASSWORD: num_pass
      DB_NAME: num_db
    ports:
      - "5001:5000"
    depends_on:
      - db

volumes:
  db_data:
